name: Build

on:
  push:
  pull_request:

env:
  LEIN_ROOT: true

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java-version: ["8", "11", "16"]
        eval-in-leiningen: ["true", "false"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - name: run tests
        run: lein test
        env:
          EVAL_IN_LEININGEN: ${{ matrix.eval-in-leiningen }}
